//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 09:57:38 AM COT 
//


package featureide;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="2" minOccurs="2"&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}var"/&gt;
 *           &lt;element ref="{}not"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "varOrNot"
})
@XmlRootElement(name = "imp")
public class Imp {

    @XmlElements({
        @XmlElement(name = "var", type = String.class),
        @XmlElement(name = "not", type = Not.class)
    })
    protected List<Object> varOrNot;

    /**
     * Default no-arg constructor
     * 
     */
    public Imp() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Imp(final List<Object> varOrNot) {
        this.varOrNot = varOrNot;
    }

    /**
     * Gets the value of the varOrNot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varOrNot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarOrNot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link Not }
     * 
     * 
     */
    public List<Object> getVarOrNot() {
        if (varOrNot == null) {
            varOrNot = new ArrayList<Object>();
        }
        return this.varOrNot;
    }

}
